# Generated by Django 6.0.4 on 2026-05-03 17:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('id_number', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
