# Generated by Django 6.0.3 on 2026-05-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='generated_card',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='generated/'),
        ),
    ]
